"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, CircleDollarSign, RefreshCw, X } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";

type Refund = { id:string; order_id:string; amount:number; reason:string; status:string; created_at:string; reviewer_note?:string; order?:{order_number:number;total_amount:number;payment_method:string;payment_status:string;status:string}; requester?:{name?:string;email?:string}; };
type Store={id:string;name:string};const money=(n:number)=>`Rp ${Number(n).toLocaleString("id-ID")}`;
export default function RefundsPage(){
  const {token,user}=useAuth();const[storeId,setStoreId]=useState(user?.store_id||"");const[stores,setStores]=useState<Store[]>([]);const[items,setItems]=useState<Refund[]>([]);const[notes,setNotes]=useState<Record<string,string>>({});const[busy,setBusy]=useState("");
  const load=useCallback(async(id:string)=>{if(!token||!id)return;const r=await fetch(`/api/refund-requests?storeId=${encodeURIComponent(id)}`,{headers:getAuthHeaders(token),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setItems(j.data||[])},[token]);
  useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{setStores(j.data||[]);if(j.data?.[0])setStoreId(j.data[0].id)}).catch(()=>{})},[token,user?.store_id]);
  useEffect(()=>{load(storeId).catch(e=>toast.error(e.message))},[load,storeId]);
  const act=async(item:Refund,decision:string)=>{if(busy)return;const note=notes[item.id]||"";if(decision==="manual_complete"&&!note.trim())return toast.error("Keterangan pengembalian tunai wajib dicatat");if(decision==="approve"&&!window.confirm(`Kirim refund ${money(item.amount)} untuk pesanan #${item.order?.order_number} ke Midtrans?`))return;setBusy(item.id);try{const r=await fetch("/api/refund-requests",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"review",requestId:item.id,decision,reviewerNote:note})});const j=await r.json();if(!r.ok)throw new Error(j.error);toast.success(decision==="approve"?"Refund dikirim ke Midtrans; status menunggu konfirmasi provider":"Permintaan diperbarui");await load(storeId)}catch(e){toast.error(e instanceof Error?e.message:"Gagal memproses permintaan")}finally{setBusy("")}};
  return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><CircleDollarSign/>Permintaan refund</h1><p className="text-sm text-slate-500">Persetujuan eksplisit, jejak audit, dan status provider.</p></div>{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3">{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>}<button onClick={()=>load(storeId)} className="rounded-xl border bg-white p-3" aria-label="Muat ulang"><RefreshCw size={17}/></button></header>
    <div className="space-y-3">{items.length?items.map(item=><article key={item.id} className="rounded-2xl bg-white p-5 shadow"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">Order #{item.order?.order_number} · {money(item.amount)}</h2><p className="text-xs text-slate-500">{new Date(item.created_at).toLocaleString("id-ID")} · {item.requester?.name||item.requester?.email||"Pelanggan"}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold capitalize">{item.status}</span></div><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{item.reason}</p><p className="mt-2 text-xs text-slate-500">Order total {money(Number(item.order?.total_amount||0))} · pembayaran {item.order?.payment_method} · {item.order?.payment_status}</p>{item.reviewer_note&&<p className="mt-2 text-sm text-slate-600">Catatan admin: {item.reviewer_note}</p>}{user?.role==="owner"&&item.status==="requested"&&<><textarea value={notes[item.id]||""} onChange={e=>setNotes({...notes,[item.id]:e.target.value})} placeholder="Catatan keputusan / bukti refund tunai" className="mt-3 min-h-16 w-full rounded-xl border p-3 text-sm"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>act(item,"reject")} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2 font-bold text-red-700"><X size={16}/>Tolak</button>{item.order?.payment_method==="snap"?<button onClick={()=>act(item,"approve")} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white"><Check size={16}/>{busy===item.id?"Mengirim…":"Setujui & kirim ke Midtrans"}</button>:<button onClick={()=>act(item,"manual_complete")} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white"><Check size={16}/>Catat refund manual selesai</button>}</div>{item.order?.payment_method==="snap"&&<p className="mt-2 text-xs text-amber-700">Refund otomatis bergantung pada aktivasi refund Midtrans dan dukungan metode pembayaran. Status selesai menunggu notifikasi Midtrans.</p>}</>}</article>):<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500">Belum ada permintaan refund.</div>}</div></main>;
}
