"use client";

import { useCallback, useEffect, useState } from "react";
import { Headset, MessageSquareWarning, Star, UtensilsCrossed } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";
type Store={id:string;name:string};type Row={id:string;status:string;created_at:string;request_type?:string;category?:string;description?:string;note?:string;reason?:string;resolution_note?:string;order?:{order_number:number;customer_name?:string};table?:{number:number};rating?:number;cashier?:{name:string}};
const requestLabels:Record<string,string>={waiter:"Panggil pelayan",bill:"Minta tagihan",utensils:"Alat makan",water:"Minta air",other:"Lainnya"};
const issueLabels:Record<string,string>={late:"Terlambat",missing_item:"Item kurang",wrong_item:"Item salah",payment:"Pembayaran",quality:"Kualitas",other:"Lainnya"};
export default function CustomerCarePage(){const{token,user}=useAuth();const[storeId,setStoreId]=useState(user?.store_id||"");const[stores,setStores]=useState<Store[]>([]);const[tab,setTab]=useState<"tables"|"incidents"|"reviews">("tables");const[tables,setTables]=useState<Row[]>([]);const[incidents,setIncidents]=useState<Row[]>([]);const[reviews,setReviews]=useState<{feedback:Row[];average:number;count:number}>({feedback:[],average:0,count:0});
 const load=useCallback(async(id:string)=>{if(!token||!id)return;try{const [a,b,c]=await Promise.all([fetch(`/api/table-service?storeId=${id}`,{headers:getAuthHeaders(token)}),fetch(`/api/order-incidents?storeId=${id}`,{headers:getAuthHeaders(token)}),fetch(`/api/dashboard/feedback?storeId=${id}`,{headers:getAuthHeaders(token)})]);const [ja,jb,jc]=await Promise.all([a.json(),b.json(),c.json()]);if(!a.ok||!b.ok||!c.ok)throw new Error(ja.error||jb.error||jc.error||"Data layanan gagal dimuat");setTables(ja.data||[]);setIncidents(jb.data||[]);setReviews(jc.data||{feedback:[],average:0,count:0})}catch(e){toast.error(e instanceof Error?e.message:"Data layanan gagal dimuat")}},[token]);
 useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{setStores(j.data||[]);if(j.data?.[0])setStoreId(j.data[0].id)}).catch(()=>{})},[token,user?.store_id]);useEffect(()=>{load(storeId)},[load,storeId]);
 const update=async(kind:"table"|"incident",id:string,status:string)=>{try{const url=kind==="table"?"/api/table-service":"/api/order-incidents";const r=await fetch(url,{method:"PATCH",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify(kind==="table"?{id,status}:{id,status,resolutionNote:status==="resolved"?"Ditangani oleh cabang":""})});const j=await r.json();if(!r.ok)throw new Error(j.error);toast.success("Status diperbarui");await load(storeId)}catch(e){toast.error(e instanceof Error?e.message:"Gagal memperbarui")}};
 return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><Headset/>Layanan pelanggan & meja</h1><p className="text-sm text-slate-500">Permintaan QR, keluhan order, dan ulasan.</p></div>{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</header>
 <nav className="mb-5 flex flex-wrap gap-2">{([["tables","Permintaan meja",UtensilsCrossed],["incidents","Masalah pesanan",MessageSquareWarning],["reviews","Ulasan",Star]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab===id?"bg-navy-950 text-white":"bg-white text-slate-600"}`}><Icon size={16}/>{label}</button>)}</nav>
 {tab==="tables"&&<div className="space-y-3">{tables.length?tables.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-4 shadow"><div><b>Meja {row.table?.number} · {requestLabels[row.request_type||""]||row.request_type}</b><p className="text-xs text-slate-500">{new Date(row.created_at).toLocaleString("id-ID")} · {row.status}{row.note?` · ${row.note}`:""}</p></div><div className="flex gap-2">{row.status==="new"&&<button onClick={()=>update("table",row.id,"acknowledged")} className="rounded-lg border px-3 py-2 text-sm font-bold">Terima</button>}{["new","acknowledged"].includes(row.status)&&<button onClick={()=>update("table",row.id,"completed")} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Selesai</button>}</div></article>):<p className="rounded-2xl bg-white p-6 text-slate-500">Tidak ada permintaan meja.</p>}</div>}
 {tab==="incidents"&&<div className="space-y-3">{incidents.length?incidents.map(row=><article key={row.id} className="rounded-2xl bg-white p-4 shadow"><div className="flex flex-wrap justify-between gap-2"><b>Order #{row.order?.order_number} · {issueLabels[row.category||""]||row.category}</b><span className="text-xs capitalize text-slate-500">{row.status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm">{row.description}</p>{row.resolution_note&&<p className="mt-2 text-xs text-slate-500">Tindak lanjut: {row.resolution_note}</p>}{["open","in_review"].includes(row.status)&&<div className="mt-3 flex gap-2"><button onClick={()=>update("incident",row.id,"in_review")} className="rounded-lg border px-3 py-2 text-sm font-bold">Tinjau</button><button onClick={()=>update("incident",row.id,"resolved")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Tandai selesai</button><button onClick={()=>update("incident",row.id,"rejected")} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Tolak</button></div>}</article>):<p className="rounded-2xl bg-white p-6 text-slate-500">Belum ada laporan masalah.</p>}</div>}
 {tab==="reviews"&&<><div className="mb-4 rounded-2xl bg-white p-5 shadow"><p className="text-sm text-slate-500">Rata-rata rating</p><b className="text-3xl">{reviews.average.toFixed(1)} / 5</b><span className="ml-3 text-sm text-slate-500">dari {reviews.count} ulasan terbaru</span></div><div className="space-y-3">{reviews.feedback.length?reviews.feedback.map(row=><article key={row.id} className="rounded-2xl bg-white p-4 shadow"><div className="flex justify-between"><b>Order #{row.order?.order_number} · {row.rating}/5 ★</b><span className="text-xs text-slate-500">{new Date(row.created_at).toLocaleDateString("id-ID")}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{row.note||"Tanpa catatan"}</p><p className="mt-1 text-xs text-slate-500">Dilayani {row.cashier?.name||"staf"}</p></article>):<p className="rounded-2xl bg-white p-6 text-slate-500">Belum ada ulasan.</p>}</div></>}
 </main>
}
