"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { Camera, Clock3, MapPin, Save, UserCheck, VideoOff } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";

type Store={id:string;name:string};type Staff={id:string;name:string;email:string;role:string};type Schedule={id:string;staff_id:string;work_date:string;starts_at:string;ends_at:string;role_label?:string|null;staff?:{name:string}};type Attendance={id:string;staff_id:string;event_type:string;work_date:string;server_timestamp:string;distance_from_store_meters:number|null;geofence_passed:boolean|null;selfie_url?:string;staff?:{name:string}};type Settings={latitude:number|null;longitude:number|null;radius_meters:number;require_location:boolean;require_selfie:boolean;allow_outside_geofence:boolean};
const dateInZone=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
function currentPosition(){return new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("Browser tidak mendukung GPS"));navigator.geolocation.getCurrentPosition(resolve,error=>reject(new Error(error.code===1?"Izin lokasi ditolak":error.code===2?"Lokasi tidak tersedia":"GPS timeout")),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
export default function StaffPage(){
 const{token,user}=useAuth();const manager=["owner","admin"].includes(user?.role||"");const[storeId,setStoreId]=useState(user?.store_id||"");const[stores,setStores]=useState<Store[]>([]);const[staff,setStaff]=useState<Staff[]>([]);const[schedules,setSchedules]=useState<Schedule[]>([]);const[attendance,setAttendance]=useState<Attendance[]>([]);const[settings,setSettings]=useState<Settings>({latitude:null,longitude:null,radius_meters:200,require_location:true,require_selfie:true,allow_outside_geofence:false});const[workDate,setWorkDate]=useState(dateInZone());
 const[staffId,setStaffId]=useState("");const[shift,setShift]=useState({workDate:dateInZone(),startsAt:"09:00",endsAt:"17:00",roleLabel:"",notes:""});const[loading,setLoading]=useState(false);const[busy,setBusy]=useState(false);const[location,setLocation]=useState<GeolocationPosition|null>(null);const[selfie,setSelfie]=useState<Blob|null>(null);const[selfieUrl,setSelfieUrl]=useState("");const[streaming,setStreaming]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const canvasRef=useRef<HTMLCanvasElement>(null);
 const load=useCallback(async(id:string,date:string)=>{if(!token||!id)return;setLoading(true);try{const r=await fetch(`/api/staff-schedules?storeId=${encodeURIComponent(id)}&from=${date}&to=${date}`,{headers:getAuthHeaders(token),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setSchedules(j.data.schedules||[]);setAttendance(j.data.attendance||[]);setStaff(j.data.users||[]);if(j.data.settings)setSettings(j.data.settings)}catch(e){toast.error(e instanceof Error?e.message:"Data staf gagal dimuat")}finally{setLoading(false)}},[token]);
 useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{setStores(j.data||[]);if(j.data?.[0])setStoreId(j.data[0].id)}).catch(()=>{})},[token,user?.store_id]);useEffect(()=>{load(storeId,workDate)},[load,storeId,workDate]);
 useEffect(()=>{return()=>{streamRef.current?.getTracks().forEach(track=>track.stop());if(selfieUrl)URL.revokeObjectURL(selfieUrl)}},[selfieUrl]);
 const startCamera=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"user"},width:{ideal:1280},height:{ideal:960}},audio:false});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setStreaming(true)}catch{toast.error("Kamera tidak dapat dibuka. Izinkan akses kamera lalu gunakan HTTPS.")}};
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setStreaming(false)};
 const capture=()=>{const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.videoWidth===0)return toast.error("Kamera belum siap");canvas.width=video.videoWidth;canvas.height=video.videoHeight;const context=canvas.getContext("2d");if(!context)return toast.error("Kamera gagal diproses");context.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!blob)return toast.error("Foto gagal diambil");if(selfieUrl)URL.revokeObjectURL(selfieUrl);setSelfie(blob);setSelfieUrl(URL.createObjectURL(blob));stopCamera();toast.success("Selfie tersimpan tanpa efek mirror")},"image/jpeg",0.88)};
 const getLocation=async()=>{try{setLocation(await currentPosition());toast.success("Lokasi GPS didapatkan") }catch(e){toast.error(e instanceof Error?e.message:"Lokasi gagal dibaca")}};
 const punch=async(eventType:"clock_in"|"clock_out")=>{if(settings.require_selfie&&!selfie)return toast.error("Ambil selfie kamera terlebih dahulu");if(settings.require_location&&!location)return toast.error("Ambil lokasi GPS terlebih dahulu");setBusy(true);try{const form=new FormData();form.set("storeId",storeId);form.set("eventType",eventType);form.set("clientTimestamp",new Date().toISOString());if(selfie)form.set("selfie",selfie,"attendance.jpg");if(location){form.set("latitude",String(location.coords.latitude));form.set("longitude",String(location.coords.longitude));form.set("accuracy",String(location.coords.accuracy))}const response=await fetch("/api/attendance",{method:"POST",headers:getAuthHeaders(token),body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Absensi gagal");toast.success(eventType==="clock_in"?"Absen masuk tercatat":"Absen pulang tercatat");setSelfie(null);setSelfieUrl("");setLocation(null);await load(storeId,workDate)}catch(e){toast.error(e instanceof Error?e.message:"Absensi gagal")}finally{setBusy(false)}};
 const saveSchedule=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch("/api/staff-schedules",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"schedule",storeId,staffId,...shift})});const j=await r.json();if(!r.ok)throw new Error(j.error);toast.success("Jadwal disimpan");await load(storeId,workDate)}catch(e){toast.error(e instanceof Error?e.message:"Jadwal gagal disimpan")}finally{setBusy(false)}};
 const saveSettings=async()=>{setBusy(true);try{const r=await fetch("/api/staff-schedules",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"attendance_settings",storeId,latitude:settings.latitude,longitude:settings.longitude,radiusMeters:settings.radius_meters,requireLocation:settings.require_location,requireSelfie:settings.require_selfie,allowOutsideGeofence:settings.allow_outside_geofence})});const j=await r.json();if(!r.ok)throw new Error(j.error);setSettings(j.data);toast.success("Pengaturan lokasi absensi disimpan")}catch(e){toast.error(e instanceof Error?e.message:"Gagal menyimpan")}finally{setBusy(false)}};
 const setBranchLocation=async()=>{try{const pos=await currentPosition();setSettings(s=>({...s,latitude:Number(pos.coords.latitude.toFixed(7)),longitude:Number(pos.coords.longitude.toFixed(7))}));toast.success("Koordinat cabang diisi dari GPS perangkat ini")}catch(e){toast.error(e instanceof Error?e.message:"GPS gagal")}};
 const clockedIn=attendance.some(row=>row.staff_id===user?.id&&row.event_type==="clock_in");const clockedOut=attendance.some(row=>row.staff_id===user?.id&&row.event_type==="clock_out");
 return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><UserCheck/>Jadwal & absensi staf</h1><p className="text-sm text-slate-500">Selfie depan disimpan tanpa mirror; lokasi dan waktu dicatat saat absen saja.</p></div><div className="flex gap-2">{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<input type="date" value={workDate} onChange={e=>setWorkDate(e.target.value)} className="rounded-xl border bg-white p-3"/></div></header>
 <section className="rounded-2xl bg-white p-5 shadow"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Absensi hari ini · {workDate}</h2><p className="text-xs text-slate-500">Jam server adalah waktu resmi. GPS akurasi: {location?`±${Math.round(location.coords.accuracy)} m`:"belum dibaca"}{settings.latitude!=null?` · radius cabang ${settings.radius_meters} m`:" · geofence belum dikonfigurasi"}</p></div><div className="flex gap-2"><button onClick={getLocation} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><MapPin size={16}/>Ambil lokasi</button><button onClick={streaming?stopCamera:startCamera} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold">{streaming?<VideoOff size={16}/>:<Camera size={16}/ >}{streaming?"Tutup kamera":"Buka kamera"}</button></div></div>
 {streaming&&<div className="mt-4 max-w-md"><video ref={videoRef} autoPlay playsInline className="aspect-[4/3] w-full rounded-2xl bg-black object-cover"/><button onClick={capture} className="mt-2 w-full rounded-xl bg-navy-950 py-3 font-bold text-white">Ambil selfie (tanpa mirror)</button></div>}{selfieUrl&&<div className="mt-4 flex items-center gap-4"><img src={selfieUrl} alt="Pratinjau selfie absensi tanpa mirror" className="h-24 w-24 rounded-2xl object-cover"/><div><b className="text-sm">Selfie siap dikirim</b><button onClick={()=>{setSelfie(null);URL.revokeObjectURL(selfieUrl);setSelfieUrl("")}} className="block text-xs text-red-600">Ambil ulang</button></div></div>}<canvas ref={canvasRef} className="hidden"/>
 <div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={()=>punch("clock_in")} disabled={busy||clockedIn} className="rounded-xl bg-emerald-600 py-3 font-bold text-white disabled:opacity-40">Absen masuk</button><button onClick={()=>punch("clock_out")} disabled={busy||!clockedIn||clockedOut} className="rounded-xl bg-navy-950 py-3 font-bold text-white disabled:opacity-40">Absen pulang</button></div></section>
 {manager&&<><form onSubmit={saveSchedule} className="mt-4 grid gap-3 rounded-2xl bg-white p-5 shadow md:grid-cols-3"><h2 className="font-black md:col-span-3"><Clock3 className="mr-2 inline"/>Atur jadwal staf</h2><select required value={staffId} onChange={e=>setStaffId(e.target.value)} className="rounded-xl border p-3"><option value="">Pilih staf</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select><input type="date" required value={shift.workDate} onChange={e=>setShift({...shift,workDate:e.target.value})} className="rounded-xl border p-3"/><input value={shift.roleLabel} onChange={e=>setShift({...shift,roleLabel:e.target.value})} placeholder="Peran/tugas (opsional)" className="rounded-xl border p-3"/><label className="text-xs">Mulai<input type="time" value={shift.startsAt} onChange={e=>setShift({...shift,startsAt:e.target.value})} className="mt-1 block w-full rounded-xl border p-3"/></label><label className="text-xs">Selesai<input type="time" value={shift.endsAt} onChange={e=>setShift({...shift,endsAt:e.target.value})} className="mt-1 block w-full rounded-xl border p-3"/></label><button disabled={busy} className="rounded-xl bg-blue-600 p-3 font-bold text-white">Simpan jadwal</button></form>
 <section className="mt-4 rounded-2xl bg-white p-5 shadow"><h2 className="font-black">Geofence absensi cabang</h2><p className="my-2 text-xs text-slate-500">Masukkan GPS cabang atau ambil lokasi perangkat ketika berada di cabang.</p><div className="grid gap-3 sm:grid-cols-3"><input type="number" step="0.0000001" value={settings.latitude??""} onChange={e=>setSettings({...settings,latitude:e.target.value===""?null:Number(e.target.value)})} placeholder="Latitude" className="rounded-xl border p-3"/><input type="number" step="0.0000001" value={settings.longitude??""} onChange={e=>setSettings({...settings,longitude:e.target.value===""?null:Number(e.target.value)})} placeholder="Longitude" className="rounded-xl border p-3"/><input type="number" min="20" max="5000" value={settings.radius_meters} onChange={e=>setSettings({...settings,radius_meters:Number(e.target.value)})} placeholder="Radius meter" className="rounded-xl border p-3"/></div><div className="my-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={settings.require_location} onChange={e=>setSettings({...settings,require_location:e.target.checked})}/> Wajib GPS</label><label><input type="checkbox" checked={settings.require_selfie} onChange={e=>setSettings({...settings,require_selfie:e.target.checked})}/> Wajib selfie</label><label><input type="checkbox" checked={settings.allow_outside_geofence} onChange={e=>setSettings({...settings,allow_outside_geofence:e.target.checked})}/> Izinkan di luar radius (tetap ditandai)</label></div><div className="flex gap-2"><button onClick={setBranchLocation} className="rounded-xl border px-4 py-2">Ambil GPS cabang</button><button onClick={saveSettings} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-navy-950 px-4 py-2 font-bold text-white"><Save size={15}/>Simpan radius</button></div></section>
 <section className="mt-4 rounded-2xl bg-white p-5 shadow"><h2 className="mb-3 font-black">Jadwal shift</h2>{schedules.length?schedules.map(s=><article key={s.id} className="mb-2 flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{s.staff?.name} · {s.role_label||"Shift"}</span><b>{s.work_date} · {s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)}</b></article>):<p className="text-sm text-slate-500">Belum ada jadwal pada tanggal ini.</p>}</section></>}
 <section className="mt-4 rounded-2xl bg-white p-5 shadow"><h2 className="mb-3 font-black">Catatan absensi</h2>{loading?<p className="text-sm text-slate-500">Memuat…</p>:attendance.length?attendance.map(a=><article key={a.id} className="mb-3 flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="h-16 w-16 overflow-hidden rounded-xl bg-slate-200">{a.selfie_url&&<img src={a.selfie_url} alt="Selfie absensi" className="h-full w-full object-cover"/>}</div><div className="min-w-48 flex-1"><b>{a.staff?.name||"Staf"} · {a.event_type==="clock_in"?"Masuk":"Pulang"}</b><p className="text-xs text-slate-500">{new Date(a.server_timestamp).toLocaleString("id-ID")} · {a.distance_from_store_meters==null?"GPS tersimpan":`${a.distance_from_store_meters} m dari cabang`}</p><p className={`text-xs ${a.geofence_passed===false?"text-amber-700":"text-emerald-700"}`}>{a.geofence_passed===false?"Di luar radius (perlu tinjauan)":"Lokasi terekam"}</p></div></article>):<p className="text-sm text-slate-500">Belum ada catatan absensi.</p>}</section>
 </main>
}
