"use client";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
import { loadMidtransSnap } from "@/lib/midtrans-client";

function NewReservationForm(){
 const search=useSearchParams(),storeId=search.get("store")||"";
 const otpClient=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false,storageKey:"selforder-reservation-otp"}}),[]);
 const [phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[accessToken,setAccessToken]=useState(""),[sent,setSent]=useState(false),[message,setMessage]=useState("");
 const [name,setName]=useState(""),[party,setParty]=useState("2"),[date,setDate]=useState("");
 const [reservationId,setReservationId]=useState(search.get("reservation")||""),[privateToken,setPrivateToken]=useState(""),[privateUrl,setPrivateUrl]=useState("");
 const bookingRef=useRef({id:"",secret:"",auth:""});
 useEffect(()=>{const saved=localStorage.getItem("reservation_private_token");if(saved)setPrivateToken(saved);bookingRef.current={id:search.get("reservation")||"",secret:saved||"",auth:""}},[search]);
 useEffect(()=>{bookingRef.current={id:reservationId,secret:privateToken,auth:accessToken}},[reservationId,privateToken,accessToken]);
 const checkPayment=async()=>{const{id,secret,auth}=bookingRef.current;if(!id||!auth||!secret)return;const q=new URLSearchParams({reservationId:id,privateToken:secret});const r=await fetch(`/api/reservations?${q}`,{headers:{"x-phone-access-token":auth}});const j=await r.json();if(r.ok){if(["paid","not_required"].includes(j.data.deposit_status)){setPrivateUrl(j.data.privateUrl);setMessage("Reservasi terkonfirmasi. Link privat reservasi Anda siap.")}else setMessage("DP masih menunggu konfirmasi Midtrans.")}else setMessage(j.error||"Gagal mengecek pembayaran")};
 const send=async()=>{const {error}=await otpClient.auth.signInWithOtp({phone});setMessage(error?.message||"Kode OTP terkirim via SMS");if(!error)setSent(true)};
 const verify=async()=>{const {data,error}=await otpClient.auth.verifyOtp({phone,token:otp,type:"sms"});if(error)return setMessage(error.message);setAccessToken(data.session?.access_token||"");setMessage("Nomor HP berhasil diverifikasi")};
 const book=async()=>{const r=await fetch("/api/reservations",{method:"POST",headers:{"Content-Type":"application/json","x-phone-access-token":accessToken},body:JSON.stringify({storeId,customerName:name,partySize:Number(party),reservedFor:new Date(date).toISOString()})});const j=await r.json();if(!r.ok){setMessage(j.error);return}setReservationId(j.data.reservation.id);setPrivateToken(j.data.privateToken);localStorage.setItem("reservation_private_token",j.data.privateToken);setMessage(`Meja ${j.data.reservation.table_id} ditahan. DP: Rp ${Number(j.data.reservation.deposit_amount).toLocaleString("id-ID")}.`);if(j.data.snapToken){const snap=await loadMidtransSnap();snap.pay(j.data.snapToken,{onSuccess:()=>{setMessage("Pembayaran diterima, memastikan status DP…");void checkPayment()},onPending:()=>setMessage("Pembayaran pending. Tekan tombol cek pembayaran setelah selesai."),onError:()=>setMessage("DP belum berhasil dibayar."),onClose:()=>setMessage("Halaman pembayaran ditutup. Anda dapat melanjutkan lewat tombol pembayaran di bawah." )})}else setPrivateUrl(j.data.privateUrl)};
 return <main className="mx-auto max-w-lg p-6"><a href={`/menu?store=${encodeURIComponent(storeId)}`} className="text-sm text-blue-700">← Kembali ke menu</a><h1 className="mt-5 text-2xl font-bold">Reservasi meja</h1><p className="mt-1 text-sm text-slate-600">Verifikasi nomor HP, DP lewat Snap, lalu link privat dan nomor meja dikirim setelah pembayaran dikonfirmasi. Meja ditahan 15 menit setelah waktu reservasi.</p><div className="mt-5 space-y-3 rounded-2xl bg-white p-5 shadow"><input placeholder="Nomor HP, contoh +628..." value={phone} onChange={e=>setPhone(e.target.value)} className="w-full rounded-xl border p-3"/><button onClick={send} className="rounded-xl bg-navy-900 px-4 py-2 text-white">Kirim OTP</button>{sent&&<><input placeholder="Kode OTP" value={otp} onChange={e=>setOtp(e.target.value)} className="w-full rounded-xl border p-3"/><button onClick={verify} className="rounded-xl bg-blue-700 px-4 py-2 text-white">Verifikasi nomor</button></>}<input placeholder="Nama" value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border p-3"/><input type="number" min="1" max="30" value={party} onChange={e=>setParty(e.target.value)} className="w-full rounded-xl border p-3"/><input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-xl border p-3"/><button disabled={!accessToken||!date||!name} onClick={book} className="w-full rounded-xl bg-emerald-700 p-3 font-bold text-white disabled:opacity-40">Buat reservasi & bayar DP</button>{reservationId&&<button onClick={checkPayment} className="w-full rounded-xl border p-3 font-bold">Cek pembayaran / kirim link privat</button>}{privateUrl&&<div className="rounded-xl bg-emerald-50 p-4"><b>Reservasi terkonfirmasi</b><p className="mt-2">Link meja privat: <a className="break-all text-blue-700 underline" href={privateUrl}>{privateUrl}</a></p></div>}{message&&<p className="text-sm text-slate-700">{message}</p>}</div></main>
}
export default function NewReservationPage(){return <Suspense fallback={<main className="p-6">Memuat reservasi…</main>}><NewReservationForm/></Suspense>}
