"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { PackagePlus, Truck } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";

type Ingredient = { id:string; name:string; unit:string; stock_quantity:number; unit_cost:number };
type Supplier = { id:string; name:string; phone?:string };
type PurchaseOrder = { id:string; order_number:string; status:string; created_at:string; supplier?:{name:string}; items:Array<{quantity_ordered:number;unit_cost:number;expires_at:string|null;ingredient?:{name:string;unit:string}}> };
type Store = { id:string; name:string };
export default function PurchasingPage(){
  const {token,user}=useAuth();
  const [storeId,setStoreId]=useState(user?.store_id||"");const [stores,setStores]=useState<Store[]>([]);
  const [suppliers,setSuppliers]=useState<Supplier[]>([]);const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[orders,setOrders]=useState<PurchaseOrder[]>([]);
  const[supplier,setSupplier]=useState({name:"",contactName:"",phone:"",email:""});const[supplierId,setSupplierId]=useState("");
  const [line,setLine]=useState({ingredientId:"",quantity:"",unitCost:"",expiresAt:""});const[lines,setLines]=useState<Array<{ingredientId:string;quantity:number;unitCost:number;expiresAt:string|null}>>([]);const[busy,setBusy]=useState(false);
  const load=useCallback(async(id:string)=>{if(!token||!id)return;const r=await fetch(`/api/purchase-orders?storeId=${encodeURIComponent(id)}`,{headers:getAuthHeaders(token),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Data pembelian gagal dimuat");setSuppliers(j.data.suppliers||[]);setIngredients(j.data.ingredients||[]);setOrders(j.data.orders||[])},[token]);
  useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{const available=j.data||[];setStores(available);if(available[0])setStoreId(available[0].id)}).catch(()=>toast.error("Cabang gagal dimuat"))},[token,user?.store_id]);
  useEffect(()=>{load(storeId).catch(e=>toast.error(e.message))},[load,storeId]);
  const saveSupplier=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch("/api/purchase-orders",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"supplier",storeId,...supplier})});const j=await r.json();if(!r.ok)throw new Error(j.error);setSupplier({name:"",contactName:"",phone:"",email:""});await load(storeId);toast.success("Pemasok disimpan")}catch(e){toast.error(e instanceof Error?e.message:"Gagal menyimpan pemasok")}finally{setBusy(false)}};
  const addLine=()=>{if(!line.ingredientId||Number(line.quantity)<=0||Number(line.unitCost)<0)return toast.error("Bahan, jumlah, dan harga wajib valid");setLines(current=>[...current,{ingredientId:line.ingredientId,quantity:Number(line.quantity),unitCost:Number(line.unitCost),expiresAt:line.expiresAt||null}]);setLine({ingredientId:"",quantity:"",unitCost:"",expiresAt:""})};
  const createPO=async()=>{if(!supplierId||!lines.length)return toast.error("Pilih pemasok dan minimal satu bahan");setBusy(true);try{const r=await fetch("/api/purchase-orders",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"purchase_order",storeId,supplierId,items:lines})});const j=await r.json();if(!r.ok)throw new Error(j.error);setLines([]);await load(storeId);toast.success(`Pesanan ${j.data.order_number} dibuat`)}catch(e){toast.error(e instanceof Error?e.message:"Pesanan pembelian gagal")}finally{setBusy(false)}};
  const receive=async(id:string)=>{if(!window.confirm("Terima seluruh bahan pesanan ini dan tambahkan ke stok? Tindakan ini tidak dapat diulang."))return;setBusy(true);try{const r=await fetch("/api/purchase-orders",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"receive",storeId,orderId:id})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load(storeId);toast.success("Stok dan biaya rata-rata bahan diperbarui")}catch(e){toast.error(e instanceof Error?e.message:"Penerimaan gagal")}finally{setBusy(false)}};
  const recordWaste=async(ingredient:Ingredient)=>{const quantity=Number(window.prompt(`Jumlah ${ingredient.name} terbuang (${ingredient.unit})?`));if(!Number.isFinite(quantity)||quantity<=0)return;const notes=window.prompt("Alasan (opsional, misalnya kedaluwarsa/rusak):")||"";setBusy(true);try{const r=await fetch("/api/purchase-orders",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"waste",storeId,ingredientId:ingredient.id,quantity,notes})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load(storeId);toast.success("Penyusutan bahan tercatat")}catch(e){toast.error(e instanceof Error?e.message:"Gagal mencatat penyusutan")}finally{setBusy(false)}};
  return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black text-navy-950">Pemasok & pembelian bahan</h1><p className="text-sm text-slate-500">Penerimaan pembelian memperbarui stok serta biaya rata-rata bahan untuk hitung HPP.</p></div>{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3">{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>}</header>
    <div className="grid gap-4 xl:grid-cols-2"><form onSubmit={saveSupplier} className="space-y-3 rounded-2xl bg-white p-5 shadow"><h2 className="font-black">Tambah pemasok</h2><input required value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})} placeholder="Nama pemasok" className="w-full rounded-xl border p-3"/><div className="grid gap-3 sm:grid-cols-2"><input value={supplier.contactName} onChange={e=>setSupplier({...supplier,contactName:e.target.value})} placeholder="Kontak" className="rounded-xl border p-3"/><input value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})} placeholder="Telepon" className="rounded-xl border p-3"/><input type="email" value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})} placeholder="Email" className="rounded-xl border p-3"/></div><button disabled={busy} className="rounded-xl bg-navy-950 px-5 py-3 font-bold text-white">Simpan pemasok</button><div className="flex flex-wrap gap-2">{suppliers.map(item=><button type="button" key={item.id} onClick={()=>setSupplierId(item.id)} className={`rounded-full border px-3 py-1 text-xs ${supplierId===item.id?"bg-blue-600 text-white":""}`}>{item.name}</button>)}</div></form>
    <section className="space-y-3 rounded-2xl bg-white p-5 shadow"><h2 className="font-black">Buat pesanan pembelian</h2><select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="w-full rounded-xl border p-3"><option value="">Pilih pemasok</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="grid gap-2 sm:grid-cols-2"><select value={line.ingredientId} onChange={e=>setLine({...line,ingredientId:e.target.value})} className="rounded-xl border p-3"><option value="">Pilih bahan</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name} ({i.unit}; stok {i.stock_quantity})</option>)}</select><input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>setLine({...line,quantity:e.target.value})} placeholder="Jumlah" className="rounded-xl border p-3"/><input type="number" min="0" step="1" value={line.unitCost} onChange={e=>setLine({...line,unitCost:e.target.value})} placeholder="Harga/unit" className="rounded-xl border p-3"/><label className="text-xs text-slate-500">Kedaluwarsa (opsional)<input type="date" value={line.expiresAt} onChange={e=>setLine({...line,expiresAt:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><button type="button" onClick={addLine} className="rounded-xl border px-4"><PackagePlus size={20}/></button></div>{lines.map((item,index)=><div key={index} className="flex justify-between rounded-lg bg-slate-50 p-2 text-sm"><span>{ingredients.find(i=>i.id===item.ingredientId)?.name} × {item.quantity}{item.expiresAt?` · ED ${item.expiresAt}`:""}</span><button type="button" onClick={()=>setLines(lines.filter((_,i)=>i!==index))} className="text-red-600">Hapus</button></div>)}<button onClick={createPO} disabled={busy||!lines.length} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-50">Buat pesanan pembelian</button></section></div>
    <section className="mt-7 space-y-3"><h2 className="font-black">Stok bahan & penyusutan</h2><div className="grid gap-2 md:grid-cols-2">{ingredients.map(i=><article key={i.id} className="flex items-center justify-between gap-3 rounded-xl bg-white p-4 shadow-sm"><div><b>{i.name}</b><p className="text-xs text-slate-500">Stok {i.stock_quantity} {i.unit} · biaya/unit Rp{Number(i.unit_cost).toLocaleString("id-ID")}</p></div><button disabled={busy||Number(i.stock_quantity)<=0} onClick={()=>recordWaste(i)} className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-bold text-amber-800">Catat terbuang</button></article>)}</div></section>
    <section className="mt-7 space-y-3"><h2 className="font-black">Riwayat pesanan pembelian</h2>{orders.length?orders.map(po=><article key={po.id} className="rounded-2xl bg-white p-5 shadow"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{po.order_number} · {po.supplier?.name}</b><p className="text-xs text-slate-500">{new Date(po.created_at).toLocaleString("id-ID")} · {po.status}</p></div>{po.status!=="received"&&po.status!=="cancelled"&&<button disabled={busy} onClick={()=>receive(po.id)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white"><Truck size={16}/> Terima bahan</button>}</div><div className="mt-3 flex flex-wrap gap-2">{po.items?.map((item,index)=><span key={index} className="rounded-full bg-blue-50 px-3 py-1 text-xs">{item.ingredient?.name}: {item.quantity_ordered} {item.ingredient?.unit} × Rp{Number(item.unit_cost).toLocaleString("id-ID")}{item.expires_at?` · kedaluwarsa ${item.expires_at}`:""}</span>)}</div></article>):<p className="rounded-2xl bg-white p-5 text-sm text-slate-500">Belum ada pesanan pembelian.</p>}</section>
  </main>
}
