"use client";

import { useCallback, useEffect, useState } from "react";
import { BarChart3, RefreshCw } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";
type Store={id:string;name:string};type ForecastDay={date:string;weekday:string;sample_days:number;items:Array<{name:string;predicted_quantity:number}>};
export default function ForecastPage(){const{token,user}=useAuth();const[storeId,setStoreId]=useState(user?.store_id||"");const[stores,setStores]=useState<Store[]>([]);const[data,setData]=useState<{forecasts:ForecastDay[];basedOnCompletedPaidOrders:number;note:string}|null>(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async(id:string)=>{if(!token||!id)return;setBusy(true);try{const r=await fetch(`/api/dashboard/forecast?storeId=${encodeURIComponent(id)}`,{headers:getAuthHeaders(token),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.data)}catch(e){toast.error(e instanceof Error?e.message:"Forecast gagal dimuat")}finally{setBusy(false)}},[token]);
 useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{setStores(j.data||[]);if(j.data?.[0])setStoreId(j.data[0].id)}).catch(()=>{})},[token,user?.store_id]);useEffect(()=>{load(storeId)},[load,storeId]);
 return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><BarChart3/>Prediksi penjualan & persiapan</h1><p className="text-sm text-slate-500">Panduan prep dari rata-rata menu terjual pada hari yang sama selama 8 minggu.</p></div><div className="flex gap-2">{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<button onClick={()=>load(storeId)} disabled={busy} className="rounded-xl border bg-white p-3"><RefreshCw size={17} className={busy?"animate-spin":""}/></button></div></header><p className="mb-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">Bukan jaminan permintaan aktual. Jumlah ini saran persiapan dan tidak mengubah stok atau membuat pembelian otomatis.</p><div className="grid gap-4 lg:grid-cols-2">{(data?.forecasts||[]).map(day=><section key={day.date} className="rounded-2xl bg-white p-5 shadow"><div className="mb-3 flex justify-between"><h2 className="font-black">{day.weekday}</h2><span className="text-xs text-slate-500">{day.date} · {day.sample_days} hari historis</span></div>{day.items.length?day.items.map(item=>{const max=Math.max(1,...day.items.map(x=>x.predicted_quantity));return <div key={item.name} className="mb-2"><div className="mb-1 flex justify-between text-sm"><span>{item.name}</span><b>{item.predicted_quantity} porsi</b></div><div className="h-2 overflow-hidden rounded-full bg-blue-50"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(4,100*item.predicted_quantity/max)}%`}}/></div></div>}):<p className="text-sm text-slate-500">Belum cukup riwayat penjualan untuk hari ini.</p>}</section>)}</div><p className="mt-5 text-xs text-slate-500">Dasar: {data?.basedOnCompletedPaidOrders||0} pesanan lunas dan selesai. {data?.note}</p></main>}
