"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { useSearchParams } from "next/navigation";
import { AnimatePresence,motion } from "framer-motion";
import { AlertCircle,ChevronRight,Clock3,MapPin,Minus,Plus,Search,ShoppingBag,SlidersHorizontal,Sparkles,Store as StoreIcon } from "lucide-react";
import toast,{Toaster} from "react-hot-toast";
import FloatingNav from "@/components/FloatingNav";
import CartDrawer from "@/components/CartDrawer";
import NotificationPrompt from "@/components/NotificationPrompt";
import AuthPrompt from "@/components/AuthPrompt";
import PaymentModal from "@/components/PaymentModal";
import QRScannerModal from "@/components/QRScannerModal";
import InstallAppPrompt from "@/components/InstallAppPrompt";
import {useAuth} from "@/contexts/AuthContext";
import type {CartItem,MenuItem,MenuOptionGroup} from "@/types";
interface Category{id:string;name:string;display_order:number} interface StoreInfo{id:string;name:string;address:string;logo?:string;is_open?:boolean;closed_reason?:string;next_open_label?:string}

export default function MenuPageContent(){
  const params=useSearchParams(),scannedStoreId=params.get("store")??"",tableNum=params.get("table")??""; const {isAuthenticated}=useAuth();
  const [activeStoreId,setActiveStoreId]=useState(scannedStoreId),[storeOptions,setStoreOptions]=useState<StoreInfo[]>([]); const storeId=scannedStoreId||activeStoreId;
  const [categories,setCategories]=useState<Category[]>([]),[items,setItems]=useState<MenuItem[]>([]),[store,setStore]=useState<StoreInfo|null>(null),[cart,setCart]=useState<CartItem[]>([]);
  const [optionItem,setOptionItem]=useState<MenuItem|null>(null),[selectedOptionIds,setSelectedOptionIds]=useState<string[]>([]);
  const [category,setCategory]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [cartOpen,setCartOpen]=useState(false),[paymentOpen,setPaymentOpen]=useState(false),[scannerOpen,setScannerOpen]=useState(false),[notificationOpen,setNotificationOpen]=useState(false),[authOpen,setAuthOpen]=useState(false);
  const searchRef=useRef<HTMLInputElement>(null),promptShown=useRef(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{let resolved=storeId;const storesResponse=await fetch("/api/stores");const storesResult=await storesResponse.json();const available:StoreInfo[]=storesResult.data??[];setStoreOptions(available);if(!resolved){resolved=available[0]?.id||"";if(resolved)setActiveStoreId(resolved);}if(!resolved)throw new Error("Belum ada toko aktif");const [s,c,m]=await Promise.all([fetch(`/api/stores/${resolved}`),fetch(`/api/menu/categories?storeId=${resolved}`),fetch(`/api/menu/items?storeId=${resolved}`)]);if(!s.ok||!c.ok||!m.ok)throw new Error();setStore((await s.json()).data);setCategories((await c.json()).data??[]);setItems((await m.json()).data??[]);}catch(error){setError(error instanceof Error&&error.message==="Belum ada toko aktif"?error.message:"Menu belum berhasil dimuat. Periksa koneksi lalu coba lagi.");}finally{setLoading(false)}},[storeId]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{const refresh=window.setInterval(()=>{void load()},60_000);return()=>window.clearInterval(refresh)},[load]);
  useEffect(()=>{if(storeId)localStorage.setItem("selforder_store_id",storeId)},[storeId]);
  useEffect(()=>{if(!localStorage.getItem("selforder_session_id"))localStorage.setItem("selforder_session_id",crypto.randomUUID());const dark=localStorage.getItem("selforder_theme")==="dark";document.documentElement.classList.toggle("dark",dark)},[]);
  const reorder=params.get("reorder");
  useEffect(()=>{if(!reorder||items.length===0)return;const raw=localStorage.getItem("selforder_reorder_cart");if(!raw)return;try{const previous=JSON.parse(raw) as Array<{menu_item_id:string;quantity:number;notes?:string;option_ids?:string[]}>;const next:CartItem[]=previous.flatMap(line=>{const item=items.find(candidate=>candidate.id===line.menu_item_id&&candidate.is_available);if(!item)return[];const validIds=(line.option_ids??[]).filter(id=>(item.option_groups??[]).some(group=>group.options.some(option=>option.id===id)));const selected=(item.option_groups??[]).flatMap(group=>group.options.filter(option=>validIds.includes(option.id)).map(option=>({group_name:group.name,option_name:option.name,price_delta:Number(option.price_delta)})));return[{...item,quantity:Math.max(1,line.quantity),notes:line.notes,option_ids:validIds,selected_options:selected}];});localStorage.removeItem("selforder_reorder_cart");if(next.length){setCart(next);toast.success("Pesanan sebelumnya dimasukkan ke keranjang")}else toast.error("Menu dari pesanan sebelumnya sudah tidak tersedia");}catch{localStorage.removeItem("selforder_reorder_cart");toast.error("Pesanan sebelumnya tidak dapat dimuat")}},[items,reorder]);
  useEffect(()=>{if(isAuthenticated||promptShown.current||localStorage.getItem("notification_prompt_seen")==="1")return;const timer=setTimeout(()=>{setNotificationOpen(true);promptShown.current=true},1800);return()=>clearTimeout(timer)},[isAuthenticated]);
  const commitItem=(item:MenuItem,optionIds:string[]=[]):boolean=>{const groups=item.option_groups??[];for(const group of groups){const count=optionIds.filter(id=>group.options.some(option=>option.id===id)).length;if(count<(group.min_select??(group.required?1:0))||count>(group.max_select??1)){toast.error(`Pilih ${group.name} terlebih dahulu`);return false;}}const selected=groups.flatMap(group=>group.options.filter(option=>optionIds.includes(option.id)).map(option=>({group_name:group.name,option_name:option.name,price_delta:Number(option.price_delta)})));setCart(prev=>{const found=prev.find(x=>x.id===item.id&&JSON.stringify([...(x.option_ids??[])].sort())===JSON.stringify([...optionIds].sort()));return found?prev.map(x=>x===found?{...x,quantity:x.quantity+1}:x):[...prev,{...item,quantity:1,option_ids:optionIds,selected_options:selected}]});toast.success(`${item.name} masuk keranjang`,{duration:1200});return true;};
  const add=(item:MenuItem)=>{if(!item.is_available)return;if(item.option_groups?.length){setOptionItem(item);setSelectedOptionIds([]);return;}commitItem(item);};
  const cartKey=(item:CartItem)=>`${item.id}:${[...(item.option_ids??[])].sort().join(",")}`;
  const subtract=(key:string)=>setCart(prev=>prev.flatMap(x=>cartKey(x)===key?(x.quantity>1?[{...x,quantity:x.quantity-1}]:[]):[x]));
  const cartCount=cart.reduce((n,x)=>n+x.quantity,0),cartTotal=cart.reduce((n,x)=>n+(Number(x.price)+(x.selected_options??[]).reduce((sum,option)=>sum+option.price_delta,0))*x.quantity,0);
  const filtered=useMemo(()=>items.filter(x=>(category==="all"||x.category_id===category)&&(`${x.name} ${x.description??""}`).toLowerCase().includes(query.toLowerCase())),[items,category,query]);
  const featured=items.filter(x=>x.is_featured&&x.is_available).slice(0,5);
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#f5f8ff] dark:bg-[#020817]"><div className="text-center"><div className="mx-auto h-12 w-12 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"/><p className="mt-4 text-sm font-semibold text-slate-500">Menyiapkan menu terbaik...</p></div></div>;
  if(error)return <div className="grid min-h-screen place-items-center bg-[#f5f8ff] p-6 text-center"><div><AlertCircle className="mx-auto h-14 w-14 text-blue-600"/><h1 className="mt-4 text-xl font-black text-navy-950">Menu tidak dapat dibuka</h1><p className="mt-2 text-slate-500">{error}</p><button onClick={load} className="mt-6 rounded-2xl bg-blue-600 px-6 py-3 font-bold text-white">Coba lagi</button></div></div>;
  if(store?.is_open===false)return <main className="grid min-h-screen place-items-center bg-gradient-to-b from-navy-950 to-blue-950 p-6 text-white"><div className="max-w-md text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-white/10"><Clock3 className="h-10 w-10 text-blue-300"/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.25em] text-blue-300">{store.name}</p><h1 className="mt-3 text-3xl font-black">Toko sedang tutup</h1><p className="mt-3 text-blue-100">Kami belum menerima pesanan saat ini.</p>{store.next_open_label&&<p className="mt-2 font-bold">Buka kembali {store.next_open_label}</p>}<p className="mt-6 text-xs text-blue-200">Menu akan tersedia kembali saat toko buka.</p></div></main>;
  return <main className="min-h-screen bg-[#f5f8ff] pb-36 text-navy-950 transition-colors dark:bg-[#020817] dark:text-white"><Toaster position="top-center"/>
    <InstallAppPrompt/>
    {notificationOpen&&!isAuthenticated&&<NotificationPrompt storeId={storeId} onComplete={()=>{setNotificationOpen(false);setAuthOpen(true)}}/>}{authOpen&&!isAuthenticated&&<AuthPrompt onComplete={()=>setAuthOpen(false)}/>} 
    <CartDrawer isOpen={cartOpen} onClose={()=>setCartOpen(false)} items={cart} onCheckout={()=>{setCartOpen(false);if(!tableNum){toast.error("Scan QR meja sebelum checkout");setScannerOpen(true)}else setPaymentOpen(true)}} onRemoveItem={key=>setCart(x=>x.filter(i=>cartKey(i)!==key))} onUpdateQuantity={(key,d)=>d<0?subtract(key):(()=>{const item=cart.find(x=>cartKey(x)===key);if(item)commitItem(item,item.option_ids??[])})()} />
    <QRScannerModal open={scannerOpen} onClose={()=>setScannerOpen(false)}/>
    {optionItem&&<div className="fixed inset-0 z-[130] grid place-items-end bg-navy-950/70 p-0 backdrop-blur-sm sm:place-items-center sm:p-4"><section className="max-h-[85vh] w-full max-w-md overflow-y-auto rounded-t-[2rem] bg-white p-5 text-navy-950 dark:bg-[#081426] dark:text-white sm:rounded-[2rem]"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">{optionItem.name}</h2><p className="text-sm text-slate-500">Pilih varian atau tambahan</p></div><button onClick={()=>setOptionItem(null)} aria-label="Tutup" className="p-2">×</button></div><div className="mt-4 space-y-4">{(optionItem.option_groups??[]).map((group:MenuOptionGroup)=><div key={group.id}><h3 className="font-bold">{group.name}{group.required&&<span className="ml-2 text-xs text-blue-600">Wajib</span>}</h3><div className="mt-2 space-y-2">{group.options.map(option=>{const checked=selectedOptionIds.includes(option.id);return <button key={option.id} onClick={()=>setSelectedOptionIds(ids=>checked?ids.filter(id=>id!==option.id):group.max_select===1?[...ids.filter(id=>!group.options.some(o=>o.id===id)),option.id]:selectedOptionIds.filter(id=>!group.options.some(o=>o.id===id)).concat([...ids.filter(id=>group.options.some(o=>o.id===id)),option.id].slice(0,group.max_select)))} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left ${checked?"border-blue-600 bg-blue-50 dark:bg-blue-950/40":"border-slate-200 dark:border-white/10"}`}><span>{option.name}</span><span>{Number(option.price_delta)>0?`+Rp ${Number(option.price_delta).toLocaleString("id-ID")}`:"Gratis"}</span></button>})}</div></div>)}</div><button onClick={()=>{if(commitItem(optionItem,selectedOptionIds))setOptionItem(null)}} className="mt-5 w-full rounded-xl bg-blue-600 py-3 font-bold text-white">Tambah ke keranjang</button></section></div>}
    {paymentOpen&&<PaymentModal isOpen={paymentOpen} onClose={()=>setPaymentOpen(false)} storeId={storeId} tableNumber={tableNum} cartItems={cart} onPaymentComplete={()=>{setCart([]);setPaymentOpen(false)}}/>}

    <header className="relative overflow-hidden bg-[#06152e] px-4 pb-16 pt-[max(1.25rem,env(safe-area-inset-top))] text-white sm:px-6">
      <div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-blue-500/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-28 -left-20 h-64 w-64 rounded-full bg-cyan-400/10 blur-3xl"/>
      <div className="relative mx-auto max-w-6xl"><div className="flex items-center justify-between"><div className="flex min-w-0 items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/10 ring-1 ring-white/15">{store?.logo?<img src={store.logo} alt="" className="h-full w-full object-cover"/>:<StoreIcon className="h-6 w-6 text-blue-300"/>}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-blue-300">Selamat datang</p><h1 className="truncate text-xl font-black sm:text-2xl">{store?.name||"SelfOrder"}</h1></div></div>{tableNum&&<div className="rounded-2xl bg-white/10 px-3 py-2 text-center ring-1 ring-white/15"><span className="block text-[9px] uppercase tracking-widest text-blue-200">Meja</span><b className="text-xl">{tableNum}</b></div>}</div>
        <div className="mt-7"><h2 className="max-w-sm text-3xl font-black leading-tight sm:text-4xl">Mau makan apa hari ini?</h2><p className="mt-2 flex items-center gap-1.5 text-xs text-blue-200"><MapPin className="h-3.5 w-3.5"/>{store?.address||"Lihat menu dulu, scan meja saat ingin memesan"}</p>{!scannedStoreId&&storeOptions.length>1&&<select value={activeStoreId} onChange={e=>{setCart([]);setActiveStoreId(e.target.value)}} className="mt-4 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-sm text-white outline-none">{storeOptions.map(option=><option className="text-navy-950" key={option.id} value={option.id}>{option.name}</option>)}</select>}</div>
        <div className="relative mt-6"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-blue-300"/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari makanan atau minuman..." className="h-14 w-full rounded-2xl border border-white/15 bg-white/10 pl-12 pr-12 text-sm text-white outline-none backdrop-blur placeholder:text-blue-200/70 focus:border-blue-400 focus:bg-white/15"/><SlidersHorizontal className="absolute right-4 top-1/2 h-5 w-5 -translate-y-1/2 text-blue-300"/></div>
      </div>
    </header>

    <div className="relative mx-auto -mt-8 max-w-6xl">
      {featured.length>0&&!query&&<section className="px-4 sm:px-6"><div className="rounded-[1.75rem] bg-blue-600 p-5 text-white shadow-xl shadow-blue-900/20"><div className="mb-4 flex items-center justify-between"><div><p className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-widest text-blue-100"><Sparkles className="h-4 w-4"/>Pilihan populer</p><h3 className="mt-1 text-xl font-black">Favorit pelanggan</h3></div><ChevronRight className="h-6 w-6 text-blue-200"/></div><div className="flex snap-x gap-3 overflow-x-auto pb-1 scrollbar-hide">{featured.map(item=><button key={item.id} onClick={()=>add(item)} className="flex min-w-[245px] snap-start items-center gap-3 rounded-2xl bg-white p-3 text-left text-navy-950 shadow-sm"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-blue-50">{item.image?<img src={item.image} alt={item.name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center"><ShoppingBag className="text-blue-300"/></div>}</div><div className="min-w-0"><b className="block truncate">{item.name}</b><span className="mt-1 block text-sm font-black text-blue-600">Rp {Number(item.price).toLocaleString("id-ID")}</span><span className="mt-2 inline-flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="h-3 w-3"/>10–15 menit</span></div></button>)}</div></div></section>}

      <nav className="sticky top-0 z-30 mt-5 border-y border-blue-100/70 bg-[#f5f8ff]/90 px-4 py-3 backdrop-blur-xl dark:border-white/10 dark:bg-[#020817]/90 sm:px-6"><div className="flex gap-2 overflow-x-auto scrollbar-hide">{[{id:"all",name:"Semua"},...categories].map(cat=><button key={cat.id} onClick={()=>setCategory(cat.id)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold transition ${category===cat.id?"bg-blue-600 text-white shadow-lg shadow-blue-600/20":"bg-white text-slate-600 ring-1 ring-blue-100 dark:bg-white/10 dark:text-slate-300 dark:ring-white/10"}`}>{cat.name}</button>)}</div></nav>

      <section className="px-4 py-6 sm:px-6"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Jelajahi menu</p><h3 className="mt-1 text-2xl font-black">{category==="all"?"Semua pilihan":categories.find(x=>x.id===category)?.name}</h3></div><span className="text-xs font-semibold text-slate-400">{filtered.length} menu</span></div>
        {filtered.length===0?<div className="rounded-[2rem] border border-dashed border-blue-200 bg-white p-12 text-center dark:bg-white/5"><Search className="mx-auto h-10 w-10 text-blue-300"/><b className="mt-3 block">Menu tidak ditemukan</b><p className="mt-1 text-sm text-slate-400">Coba kata kunci atau kategori lain.</p></div>:<div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">{filtered.map((item,index)=>{const selected=cart.find(x=>x.id===item.id);return <motion.article key={item.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:Math.min(index*.025,.25)}} className={`group overflow-hidden rounded-[1.35rem] bg-white shadow-[0_8px_30px_rgba(15,39,80,.08)] ring-1 ring-blue-100/70 dark:bg-[#09162b] dark:ring-white/10 ${!item.is_available?"opacity-60":""}`}><div className="relative aspect-[1/1] overflow-hidden bg-blue-50 dark:bg-navy-900">{item.image?<img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="grid h-full place-items-center"><ShoppingBag className="h-9 w-9 text-blue-200"/></div>}{item.is_featured&&<span className="absolute left-2 top-2 rounded-full bg-blue-600 px-2 py-1 text-[9px] font-extrabold text-white shadow">POPULER</span>}{!item.is_available&&<div className="absolute inset-0 grid place-items-center bg-navy-950/55"><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-navy-950">Habis</span></div>}</div><div className="p-3"><h4 className="line-clamp-1 text-sm font-extrabold">{item.name}</h4><p className="mt-1 line-clamp-2 min-h-8 text-[11px] leading-4 text-slate-400">{item.description||"Dibuat segar khusus untuk Anda"}</p><div className="mt-3 flex items-end justify-between gap-1"><span className="text-sm font-black text-blue-600">Rp {Number(item.price).toLocaleString("id-ID")}</span>{item.is_available&&(selected?<div className="flex items-center rounded-xl bg-blue-50 p-1 dark:bg-white/10"><button onClick={()=>subtract(item.id)} className="grid h-7 w-7 place-items-center text-blue-700"><Minus className="h-3.5 w-3.5"/></button><b className="w-5 text-center text-xs">{selected.quantity}</b><button onClick={()=>add(item)} className="grid h-7 w-7 place-items-center rounded-lg bg-blue-600 text-white"><Plus className="h-3.5 w-3.5"/></button></div>:<button onClick={()=>add(item)} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-600/25"><Plus className="h-5 w-5"/></button>)}</div></div></motion.article>})}</div>}
      </section>
    </div>
    <AnimatePresence>{cartCount>0&&<motion.button initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} exit={{y:80,opacity:0}} onClick={()=>setCartOpen(true)} style={{bottom:"calc(6.5rem + env(safe-area-inset-bottom, 0px))"}} className="fixed left-4 right-4 z-[60] mx-auto flex max-w-md items-center gap-3 rounded-2xl bg-blue-600 p-3.5 text-white shadow-2xl shadow-blue-950/35 ring-4 ring-white/80 dark:ring-[#020817]/80"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/15 font-black">{cartCount}</span><span className="flex-1 text-left"><b className="block text-sm">Lihat keranjang</b><small className="text-blue-100">Siap untuk checkout</small></span><b>Rp {cartTotal.toLocaleString("id-ID")}</b></motion.button>}</AnimatePresence>
    <FloatingNav cartCount={cartCount} onCartClick={()=>setCartOpen(true)} onScanClick={()=>setScannerOpen(true)} onSearchClick={()=>{searchRef.current?.focus();searchRef.current?.scrollIntoView({behavior:"smooth",block:"center"})}} onProfileClick={()=>setAuthOpen(true)}/>
  </main>
}
