"use client";
import {useCallback,useEffect,useState} from "react";
import {BadgePercent,Building2,ExternalLink,Loader2,Save} from "lucide-react";
import toast,{Toaster} from "react-hot-toast";
import {getAuthHeaders,useAuth} from "@/contexts/AuthContext";
type Store={id:string;name:string}; const EMPTY={promo_name:"",promo_description:"",promo_qr_url:"",promo_active:"false"};
export default function PromoPage(){const {token,user}=useAuth();const [stores,setStores]=useState<Store[]>([]),[storeId,setStoreId]=useState(""),[form,setForm]=useState(EMPTY),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  useEffect(()=>{if(!token)return;fetch("/api/stores",{headers:getAuthHeaders(token)}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);const rows=result.data??[];setStores(rows);setStoreId(user?.store_id||rows[0]?.id||"");}).catch(e=>toast.error(e.message||"Gagal memuat toko"));},[token,user?.store_id]);
  const load=useCallback(async()=>{if(!storeId)return;setLoading(true);const response=await fetch(`/api/store-settings?storeId=${storeId}`,{headers:getAuthHeaders(token)});const result=await response.json();setLoading(false);response.ok?setForm({...EMPTY,...result.data}):toast.error(result.error||"Gagal memuat promo")},[storeId,token]); useEffect(()=>{load()},[load]);
  const save=async()=>{if(!storeId)return toast.error("Pilih toko terlebih dahulu");setSaving(true);const response=await fetch("/api/store-settings",{method:"PUT",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({storeId,...form})});const result=await response.json();setSaving(false);response.ok?toast.success("Promo struk disimpan"):toast.error(result.error||"Gagal menyimpan")};
  return <main className="p-5 lg:p-10"><Toaster/><div className="mx-auto max-w-3xl"><div className="mb-7 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg"><BadgePercent/></span><div><h1 className="text-3xl font-black text-navy-950">Promo pada struk</h1><p className="text-sm text-navy-500">QR promo otomatis tampil pada invoice pelanggan.</p></div></div>
    <section className="rounded-[2rem] border border-blue-100 bg-white p-6 shadow-xl shadow-blue-950/5"><label className="label-field">Toko / cabang</label><div className="relative mb-5"><Building2 className="absolute left-4 top-3.5 h-5 w-5 text-blue-600"/><select value={storeId} onChange={e=>setStoreId(e.target.value)} className="input-field w-full pl-12 font-semibold"><option value="">Pilih toko</option>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></div>
    {loading&&storeId?<div className="grid h-56 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600"/></div>:<><label className="mb-4 flex items-center justify-between rounded-2xl bg-blue-50 p-4 font-bold text-navy-900">Aktifkan promo<input type="checkbox" checked={form.promo_active==="true"} onChange={e=>setForm(p=>({...p,promo_active:String(e.target.checked)}))} className="h-5 w-5 accent-blue-600"/></label><label className="label-field">Nama promo</label><input className="input-field mb-4 w-full" value={form.promo_name} onChange={e=>setForm(p=>({...p,promo_name:e.target.value}))} placeholder="Diskon kunjungan berikutnya"/><label className="label-field">Deskripsi singkat</label><textarea className="input-field mb-4 h-24 w-full" value={form.promo_description} onChange={e=>setForm(p=>({...p,promo_description:e.target.value}))}/><label className="label-field">Tujuan QR promo</label><div className="relative"><ExternalLink className="absolute left-4 top-3.5 h-4 w-4 text-navy-400"/><input type="url" className="input-field w-full pl-11" value={form.promo_qr_url} onChange={e=>setForm(p=>({...p,promo_qr_url:e.target.value}))} placeholder="https://..."/></div><button onClick={save} disabled={saving||!storeId} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 py-4 font-bold text-white disabled:opacity-40">{saving?<Loader2 className="animate-spin"/>:<Save/>}Simpan promo</button></>}</section></div></main>}
