"use client";
import { useCallback, useEffect, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { useAuth, getAuthHeaders } from "@/contexts/AuthContext";

type Report = { orders: any[]; totals: { orderCount: number; sales: number }; products: { name: string; quantity: number; sales: number }[]; hours: Record<string, number>; methods: Record<string, number>; shifts: any[] };
const money = (n: number) => `Rp ${Math.round(n).toLocaleString("id-ID")}`;
const currentDateInJakarta = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const thirtyDaysAgoInJakarta = () => new Date(Date.parse(`${currentDateInJakarta()}T00:00:00Z`) - 30 * 86400000).toISOString().slice(0, 10);
export default function ReportsPage() {
  const { token, user } = useAuth();
  const [data, setData] = useState<Report | null>(null);
  const [from, setFrom] = useState(thirtyDaysAgoInJakarta);
  const [to, setTo] = useState(currentDateInJakarta);
  const load = useCallback(async () => { if (!token) return; const response = await fetch(`/api/dashboard/reports?storeId=${user?.store_id || ""}&from=${from}&to=${to}`, { headers: getAuthHeaders(token) }); const result = await response.json(); if (response.ok) setData(result.data); }, [token, user?.store_id, from, to]);
  useEffect(() => { load(); }, [load]);
  const exportCsv = () => { if (!data) return; const rows = [["Jenis", "Nama", "Jumlah", "Penjualan"], ...data.products.map(p => ["Menu", p.name, p.quantity, p.sales]), ...Object.entries(data.methods).map(([name, sales]) => ["Pembayaran", name, "", sales]), ...Object.entries(data.hours).map(([hour, count]) => ["Jam ramai", hour, count, ""])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" })); link.download = `laporan-${from}-${to}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <main className="p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Laporan penjualan</h1><p className="text-sm text-slate-500">Ringkasan cabang dan ekspor CSV</p></div><div className="flex gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border p-2"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border p-2"/><button onClick={load} className="rounded-xl border p-2" aria-label="Muat ulang"><RefreshCw size={18}/></button><button onClick={exportCsv} className="flex items-center gap-2 rounded-xl bg-navy-900 px-4 py-2 text-white"><Download size={17}/> CSV</button></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow"><p className="text-sm text-slate-500">Omzet dibayar</p><b className="text-2xl">{money(data?.totals.sales || 0)}</b></section><section className="rounded-2xl bg-white p-5 shadow"><p className="text-sm text-slate-500">Jumlah order</p><b className="text-2xl">{data?.totals.orderCount || 0}</b></section></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow"><h2 className="font-bold">Menu terlaris</h2>{data?.products.slice(0,10).map(p=><div key={p.name} className="flex justify-between border-b py-2 text-sm"><span>{p.name} · {p.quantity} terjual</span><b>{money(p.sales)}</b></div>)}</section><section className="rounded-2xl bg-white p-5 shadow"><h2 className="font-bold">Metode pembayaran</h2>{Object.entries(data?.methods || {}).map(([name,sales])=><div key={name} className="flex justify-between border-b py-2 text-sm"><span>{name}</span><b>{money(sales)}</b></div>)}<h3 className="mt-4 font-bold">Jam ramai</h3>{Object.entries(data?.hours || {}).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([hour,count])=><p key={hour} className="text-sm">{hour}:00 — {count} order</p>)}</section></div><section className="mt-4 rounded-2xl bg-white p-5 shadow"><h2 className="font-bold">Selisih kas shift</h2><p className="text-xs text-slate-500">Kas seharusnya dihitung dari transaksi tunai yang tercatat pada shift.</p>{data?.shifts.map(shift=><p key={shift.id} className="mt-2 text-sm">{new Date(shift.opened_at).toLocaleString("id-ID")} · kas awal {money(Number(shift.opening_cash))} · seharusnya {money(Number(shift.expected_cash))} · kas akhir {money(Number(shift.closing_cash))} · selisih {money(Number(shift.cash_difference))}</p>)}</section></main>;
}
