"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FileText, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { getAuthHeaders, useAuth } from "@/contexts/AuthContext";
import toast, { Toaster } from "react-hot-toast";
type Store={id:string;name:string};type Doc={id:string;document_type:string;title:string;content:string;version:number;status:string};type Faq={id:string;question:string;answer:string;display_order:number;is_published:boolean};
const names:Record<string,string>={privacy:"Kebijakan Privasi",terms:"Syarat Penggunaan",refund:"Pembatalan & Refund"};
export default function PoliciesPage(){const{token,user}=useAuth();const[storeId,setStoreId]=useState(user?.store_id||"");const[stores,setStores]=useState<Store[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[faqs,setFaqs]=useState<Faq[]>([]);const[type,setType]=useState("privacy");const[title,setTitle]=useState(names.privacy);const[content,setContent]=useState("");const[publish,setPublish]=useState(false);const[faq,setFaq]=useState({question:"",answer:"",displayOrder:0});const[busy,setBusy]=useState(false);
 const load=useCallback(async(id:string)=>{if(!token)return;const url=`/api/policies?includeDraft=1${id?`&storeId=${encodeURIComponent(id)}`:""}`;const r=await fetch(url,{headers:getAuthHeaders(token),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);const documents=(j.data.documents||[]) as Doc[];setDocs(documents);setFaqs(j.data.faqs||[]);const selected=documents.find(d=>d.document_type===type);if(selected){setTitle(selected.title);setContent(selected.content)}},[token,type]);
 useEffect(()=>{if(user?.store_id){setStoreId(user.store_id);return}fetch("/api/stores",{headers:getAuthHeaders(token)}).then(r=>r.json()).then(j=>{setStores(j.data||[]);if(j.data?.[0])setStoreId(j.data[0].id)}).catch(()=>{})},[token,user?.store_id]);useEffect(()=>{load(storeId).catch(e=>toast.error(e.message))},[load,storeId]);
 useEffect(()=>{const doc=docs.find(d=>d.document_type===type);setTitle(doc?.title||names[type]);setContent(doc?.content||"");setPublish(false)},[type,docs]);
 const saveDoc=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch("/api/policies",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"document",storeId:storeId||null,documentType:type,title,content,publish})});const j=await r.json();if(!r.ok)throw new Error(j.error);toast.success(publish?"Versi baru dipublikasikan":"Draft versi baru disimpan");setPublish(false);await load(storeId)}catch(e){toast.error(e instanceof Error?e.message:"Dokumen gagal disimpan")}finally{setBusy(false)}};
 const saveFaq=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch("/api/policies",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({action:"faq",storeId:storeId||null,...faq,publish:true})});const j=await r.json();if(!r.ok)throw new Error(j.error);setFaq({question:"",answer:"",displayOrder:0});toast.success("FAQ diterbitkan");await load(storeId)}catch(e){toast.error(e instanceof Error?e.message:"FAQ gagal disimpan")}finally{setBusy(false)}};
 const removeFaq=async(id:string)=>{if(!window.confirm("Hapus FAQ ini?"))return;const r=await fetch(`/api/policies?faqId=${id}`,{method:"DELETE",headers:getAuthHeaders(token)});const j=await r.json();if(!r.ok)return toast.error(j.error);await load(storeId)};
 return <main className="p-5 md:p-8"><Toaster position="top-right"/><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><ShieldCheck/>Pusat bantuan & kebijakan</h1><p className="text-sm text-slate-500">Setiap publikasi membuat versi baru; isi kebijakan harus ditinjau sebelum tayang.</p></div>{stores.length>0&&<select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">Kebijakan global</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</header>
 <div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><form onSubmit={saveDoc} className="space-y-3 rounded-2xl bg-white p-5 shadow"><h2 className="flex items-center gap-2 font-black"><FileText size={18}/>Dokumen kebijakan</h2><select value={type} onChange={e=>setType(e.target.value)} className="w-full rounded-xl border p-3">{Object.entries(names).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select><p className="text-xs text-slate-500">Versi terbaru: {docs.find(d=>d.document_type===type)?.version||"belum ada"}. Draft lama tetap tersimpan.</p><input required minLength={3} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className="w-full rounded-xl border p-3" placeholder="Judul dokumen"/><textarea required minLength={50} maxLength={30000} value={content} onChange={e=>setContent(e.target.value)} className="min-h-[320px] w-full rounded-xl border p-3 text-sm leading-6" placeholder="Tulis kebijakan dalam teks biasa. Jelaskan proses, biaya, tenggat, pengecualian, dan cara menghubungi cabang."/><label className="flex items-start gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)} className="mt-0.5"/><span>Publikasikan versi baru sekarang. Untuk privacy/terms, pelanggan akan diminta menyetujui dokumen yang tayang sebelum checkout. Draft tetap privat.</span></label><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-navy-950 px-5 py-3 font-bold text-white"><Save size={16}/>{busy?"Menyimpan…":publish?"Simpan & publikasikan":"Simpan sebagai draft"}</button></form>
 <div className="space-y-4"><form onSubmit={saveFaq} className="space-y-3 rounded-2xl bg-white p-5 shadow"><h2 className="font-black">Tambah FAQ</h2><input required minLength={5} value={faq.question} onChange={e=>setFaq({...faq,question:e.target.value})} className="w-full rounded-xl border p-3" placeholder="Pertanyaan pelanggan"/><textarea required minLength={5} value={faq.answer} onChange={e=>setFaq({...faq,answer:e.target.value})} className="min-h-24 w-full rounded-xl border p-3" placeholder="Jawaban singkat dan jelas"/><button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-bold text-white"><Plus size={16}/>Terbitkan FAQ</button></form><section className="rounded-2xl bg-white p-5 shadow"><h2 className="mb-3 font-black">FAQ terbit</h2>{faqs.length?faqs.map(item=><article key={item.id} className="mb-3 flex justify-between gap-3 border-b pb-3"><div><b className="text-sm">{item.question}</b><p className="whitespace-pre-wrap text-sm text-slate-600">{item.answer}</p></div><button onClick={()=>removeFaq(item.id)} aria-label="Hapus FAQ" className="h-fit rounded-lg p-2 text-red-600"><Trash2 size={16}/></button></article>):<p className="text-sm text-slate-500">Belum ada FAQ.</p>}</section><aside className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">Template ini adalah alat pengelolaan konten, bukan nasihat hukum. Lengkapi kebijakan sesuai praktik bisnis, payment gateway, dan aturan yang berlaku; minta tinjauan profesional sebelum publikasi.</aside></div></div>
 </main>
}
