"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {Barcode,Banknote,Camera,CheckCircle2,Loader2} from "lucide-react";
import toast,{Toaster} from "react-hot-toast";
import {getAuthHeaders,useAuth} from "@/contexts/AuthContext";
export default function PosPage(){
  const {token}=useAuth();const [code,setCode]=useState(""),[loading,setLoading]=useState(false),[scanning,setScanning]=useState(false);const controls=useRef<{stop:()=>void}|null>(null),video=useRef<HTMLVideoElement>(null);
  const stopScan=()=>{controls.current?.stop();controls.current=null;setScanning(false)};
  const confirm=async(value:string)=>{const orderId=value.trim();if(!orderId)return;setLoading(true);try{const response=await fetch("/api/payment/cash",{method:"POST",headers:{"Content-Type":"application/json",...getAuthHeaders(token)},body:JSON.stringify({orderId,confirm:true})});const result=await response.json();if(!response.ok)throw new Error(result.error);toast.success(`Pembayaran antrean #${result.data.order_number} terkonfirmasi`);setCode("");stopScan();}catch(error){toast.error(error instanceof Error?error.message:"Barcode tidak valid")}finally{setLoading(false)}};
  const startScan=async()=>{try{setScanning(true);await new Promise(resolve=>setTimeout(resolve,50));if(!video.current)throw new Error("Scanner belum siap");const {BrowserMultiFormatReader}=await import("@zxing/browser");const reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"}}},video.current,result=>{if(result){setCode(result.getText());confirm(result.getText())}})}catch(error){setScanning(false);toast.error(error instanceof Error?error.message:"Kamera gagal dibuka")}};
  useEffect(()=>stopScan,[]);
  return <main className="min-h-screen bg-gradient-to-br from-navy-950 to-blue-950 p-5 text-white lg:p-10"><Toaster/><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.25em] text-blue-300">Cashier workspace</p><h1 className="mt-2 text-4xl font-black">POS & Konfirmasi Tunai</h1><p className="mt-2 text-navy-300">Scanner Code 128 lintas-browser untuk meneruskan pesanan ke dapur.</p><div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-[2rem] bg-white p-6 text-navy-950 shadow-2xl"><div className="mb-5 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white"><Camera/></span><div><h2 className="font-bold">Scanner kamera</h2><p className="text-xs text-navy-500">Chrome, Safari, Firefox, dan Edge</p></div></div><video ref={video} muted playsInline className={scanning?"aspect-video w-full rounded-2xl bg-black object-cover":"hidden"}/>{scanning?<button onClick={stopScan} className="mt-4 w-full rounded-xl bg-blue-50 py-3 font-bold text-blue-700">Tutup kamera</button>:<button onClick={startScan} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 py-4 font-bold text-white"><Barcode/>Mulai scan barcode</button>}</section><section className="rounded-[2rem] bg-white p-6 text-navy-950 shadow-2xl"><div className="mb-5 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white"><Banknote/></span><div><h2 className="font-bold">Input manual</h2><p className="text-xs text-navy-500">Cadangan jika kamera tidak tersedia</p></div></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();confirm(code)}}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="CASH-xxxxxxxx-..." className="w-full rounded-2xl border-2 border-navy-100 p-4 font-mono outline-none focus:border-blue-500"/><button disabled={loading||!code} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-navy-950 py-4 font-bold text-white disabled:opacity-40">{loading?<Loader2 className="animate-spin"/>:<CheckCircle2/>}Konfirmasi pembayaran</button></form></section></div></div></main>;
}
