import http from "node:http";
import net from "node:net";

const port=Number(process.env.ESC_POS_BRIDGE_PORT||9123);
const printerHost=process.env.ESC_POS_PRINTER_HOST;
const printerPort=Number(process.env.ESC_POS_PRINTER_PORT||9100);
const allowedOrigin=process.env.SELFORDER_ORIGIN||"";
const ESC=Buffer.from([0x1b]),GS=Buffer.from([0x1d]);
const clean=value=>String(value??"").normalize("NFKD").replace(/[^\x20-\x7e\n]/g,"?");
const line=value=>Buffer.from(`${clean(value)}\n`,`ascii`);
function ticket(order){const out=[ESC,Buffer.from("@"),ESC,Buffer.from("a\x01"),GS,Buffer.from("!\x11"),line("SELFORDER"),GS,Buffer.from("!\x00"),line(`ORDER #${order.number}`),line("--------------------------------"),line(order.orderType==="pickup"?`PICKUP ${order.pickupAt||""}`:`TABLE ${order.tableNumber??"-"}`),line(order.customerName||""),line(`ORDERED ${new Date(order.createdAt).toLocaleString("id-ID")}`),line(`READY ${order.estimatedReadyAt?new Date(order.estimatedReadyAt).toLocaleTimeString("id-ID"):"-"}`),line("--------------------------------")];for(const item of order.items||[]){out.push(line(`${item.quantity} x ${item.name}`));if(item.notes)out.push(line(`   NOTE: ${item.notes}`))}if(order.notes)out.push(line(`NOTE: ${order.notes}`));out.push(line("--------------------------------"),line("\n\n"),GS,Buffer.from("V\x41\x00"));return Buffer.concat(out)}
function sendToPrinter(data){return new Promise((resolve,reject)=>{const socket=net.createConnection({host:printerHost,port:printerPort},()=>socket.end(data));socket.on("error",reject);socket.on("close",()=>resolve())})}
http.createServer(async(req,res)=>{const origin=req.headers.origin||"";if(!allowedOrigin||origin!==allowedOrigin){res.writeHead(403);return res.end("configure SELFORDER_ORIGIN to the exact dashboard origin")}res.setHeader("Access-Control-Allow-Origin",allowedOrigin);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","POST, OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}if(req.method!=="POST"||req.url!=="/print"){res.writeHead(404);return res.end("not found")}if(!printerHost){res.writeHead(503);return res.end("Set ESC_POS_PRINTER_HOST to your printer IP")}let raw="";for await(const chunk of req)raw+=chunk;try{const payload=JSON.parse(raw);if(payload.type!=="kitchen_ticket"||!payload.order?.number)throw new Error("invalid ticket");await sendToPrinter(ticket(payload.order));res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify({ok:true}))}catch(error){res.writeHead(502,{"Content-Type":"application/json"});res.end(JSON.stringify({error:error instanceof Error?error.message:"printer error"}))}}).listen(port,"127.0.0.1",()=>console.log(`ESC/POS bridge listening at http://127.0.0.1:${port}; printer ${printerHost||"not configured"}:${printerPort}`));
