"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BellOff,BellRing,LayoutDashboard,Loader2,LogOut,Moon,Send,ShieldCheck,Sun,WalletCards} from "lucide-react";
import toast,{Toaster} from "react-hot-toast";
import {useAuth,useRole} from "@/contexts/AuthContext";
import {disablePush,enablePush,showTestNotification} from "@/lib/push-client";
export default function ProfilePage(){const {user,logout}=useAuth();const {isStaff}=useRole();const [dark,setDark]=useState(false),[permission,setPermission]=useState<NotificationPermission>("default"),[busy,setBusy]=useState(false);useEffect(()=>{const enabled=localStorage.getItem("selforder_theme")==="dark";setDark(enabled);document.documentElement.classList.toggle("dark",enabled);if("Notification" in window)setPermission(Notification.permission)},[]);const toggle=()=>{const next=!dark;setDark(next);localStorage.setItem("selforder_theme",next?"dark":"light");document.documentElement.classList.toggle("dark",next)};const activate=async()=>{setBusy(true);try{await enablePush({userId:user?.id});setPermission(Notification.permission);toast.success("Notifikasi aktif dan tes sudah dikirim")}catch(error){setPermission("Notification" in window?Notification.permission:"denied");toast.error(error instanceof Error?error.message:"Gagal mengaktifkan notifikasi")}finally{setBusy(false)}};const test=async()=>{try{await showTestNotification();toast.success("Notifikasi tes dikirim")}catch(error){toast.error(error instanceof Error?error.message:"Tes gagal")}};const reset=async()=>{setBusy(true);await disablePush();setBusy(false);toast.success("Subscription direset. Izin browser dapat diubah melalui Site Settings.")};return <main className="profile-shell min-h-screen bg-blue-50 p-4 text-navy-950 md:p-10"><Toaster/><div className="mx-auto max-w-2xl"><Link href="/menu" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-blue-700"><ArrowLeft className="h-4 w-4"/>Kembali</Link><section className="overflow-hidden rounded-[2rem] bg-white shadow-2xl shadow-blue-950/10"><div className="bg-gradient-to-br from-navy-950 to-blue-800 p-8 text-white"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-white/15 text-3xl font-black">{(user?.name||user?.email||"U")[0].toUpperCase()}</div><h1 className="mt-5 text-3xl font-black">{user?.name||"Pengguna SelfOrder"}</h1><p className="text-blue-200">{user?.email||"Sesi tamu"}</p><span className="mt-3 inline-flex items-center gap-1 rounded-full bg-white/10 px-3 py-1 text-xs font-bold capitalize"><ShieldCheck className="h-3 w-3"/>{user?.role||"guest"}</span></div><div className="space-y-4 p-6">
  <div className="flex items-center justify-between rounded-2xl border border-navy-100 p-4"><div className="flex items-center gap-3">{dark?<Moon/>:<Sun/>}<div><b className="block">Tema aplikasi</b><span className="text-xs text-navy-500">{dark?"Navy gelap & hitam":"Navy & putih"}</span></div></div><button onClick={toggle} className={`h-7 w-12 rounded-full p-1 transition ${dark?"bg-blue-600":"bg-navy-200"}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${dark?"translate-x-5":""}`}/></button></div>
  <div className="rounded-2xl border border-blue-100 p-4"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${permission==="granted"?"bg-blue-600 text-white":"bg-blue-50 text-blue-600"}`}>{permission==="granted"?<BellRing/>:<BellOff/>}</span><div><b className="block">Notifikasi pesanan</b><p className="mt-1 text-xs leading-5 text-slate-500">Status: <strong className="capitalize">{permission==="granted"?"aktif":permission==="denied"?"diblokir browser":"belum diaktifkan"}</strong>. Update tampil sebagai bubble notifikasi sistem.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2">{permission!=="granted"?<button disabled={busy} onClick={activate} className="col-span-2 flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<BellRing className="h-4 w-4"/>}Aktifkan & tes</button>:<><button onClick={test} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white"><Send className="h-4 w-4"/>Kirim tes</button><button disabled={busy} onClick={reset} className="rounded-xl bg-blue-50 py-3 text-sm font-bold text-blue-700">Reset</button></>}</div>{permission==="denied"&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs text-blue-800">Buka ikon gembok di address bar → Site settings → Notifications → Allow, lalu kembali dan tekan Aktifkan.</p>}</div>
  {user&&<Link href="/wallet" className="flex items-center gap-3 rounded-2xl bg-blue-600 p-4 font-bold text-white"><WalletCards/>Saldo, top up & penarikan</Link>}{isStaff&&<Link href="/dashboard" className="flex items-center gap-3 rounded-2xl bg-blue-50 p-4 font-bold text-blue-800"><LayoutDashboard/>Buka dashboard</Link>}<button onClick={logout} className="flex w-full items-center gap-3 rounded-2xl bg-red-50 p-4 font-bold text-red-600"><LogOut/>Keluar dari akun</button></div></section></div></main>}
