"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CircleHelp, FileText, ShieldCheck } from "lucide-react";
import toast, { Toaster } from "react-hot-toast";
type Doc={id:string;document_type:string;title:string;content:string;version:number;published_at:string};type Faq={id:string;question:string;answer:string};type Store={id:string;name:string};
const labels:Record<string,string>={privacy:"Kebijakan Privasi",terms:"Syarat Penggunaan",refund:"Pembatalan & Refund"};
export default function HelpPage(){const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[docs,setDocs]=useState<Doc[]>([]);const[faqs,setFaqs]=useState<Faq[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{const queryStore=new URLSearchParams(window.location.search).get("store");const preferred=queryStore||localStorage.getItem("selforder_store_id")||"";const load=async(id:string)=>{setStoreId(id);const r=await fetch(`/api/policies${id?`?storeId=${encodeURIComponent(id)}`:""}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setDocs(j.data.documents||[]);setFaqs(j.data.faqs||[])};fetch("/api/stores").then(r=>r.json()).then(async result=>{const stores=(result.data||[]) as Store[];const selected=stores.find(s=>s.id===preferred)||stores[0];if(selected){setStoreName(selected.name);await load(selected.id)}else await load("")}).catch(e=>toast.error(e instanceof Error?e.message:"Bantuan gagal dimuat")).finally(()=>setLoading(false))},[]);
 const visibleTypes=["privacy","terms","refund"];
 return <main className="min-h-screen bg-blue-50 p-4 text-navy-950 md:p-8"><Toaster position="top-center"/><div className="mx-auto max-w-3xl"><Link href="/menu" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700"><ArrowLeft size={16}/> Kembali ke menu</Link><header className="my-6 rounded-3xl bg-gradient-to-br from-navy-950 to-blue-800 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-blue-200">{storeName||"SelfOrder"}</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-black"><CircleHelp/>Pusat bantuan</h1><p className="mt-2 text-sm text-blue-100">FAQ, privasi, ketentuan pemesanan, dan cara mengajukan bantuan/refund.</p></header>
 <section className="space-y-3"><h2 className="flex items-center gap-2 font-black"><FileText size={18}/>Kebijakan</h2>{visibleTypes.map(type=>{const doc=docs.find(item=>item.document_type===type);return <article key={type} id={type} className="scroll-mt-5 rounded-2xl bg-white p-5 shadow"><h3 className="flex items-center gap-2 font-black"><ShieldCheck size={17} className="text-blue-600"/>{doc?.title||labels[type]}</h3>{doc?<><p className="mt-1 text-[11px] text-slate-400">Versi {doc.version} · berlaku sejak {doc.published_at?new Date(doc.published_at).toLocaleDateString("id-ID"):"—"}</p><div className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{doc.content}</div></>:<p className="mt-2 text-sm text-slate-500">{loading?"Memuat…":"Kebijakan ini belum dipublikasikan oleh cabang."}</p>}</article>})}</section>
 <section className="mt-7 space-y-3"><h2 className="font-black">Pertanyaan umum</h2>{faqs.length?faqs.map(item=><details key={item.id} className="rounded-2xl bg-white p-5 shadow"><summary className="cursor-pointer font-bold">{item.question}</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.answer}</p></details>):<p className="rounded-2xl bg-white p-5 text-sm text-slate-500">FAQ belum ditambahkan oleh cabang.</p>}</section>
 <section className="mt-7 rounded-2xl bg-white p-5 shadow"><h2 className="font-black">Ada masalah dengan pesanan?</h2><p className="mt-1 text-sm text-slate-500">Buka tautan bantuan pada halaman status pesanan agar laporan terkait dengan order yang benar.</p><Link href="/orders" className="mt-3 inline-flex rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Riwayat pesanan</Link></section>
 </div></main>;
}
